pageWPF
Label pageWPF::ID
Referenced by pageWPF.
Label pageWPF::label1
Referenced by pageWPF.
Label pageWPF::label2
Referenced by pageWPF.
Label pageWPF::label3
Referenced by pageWPF.
Label pageWPF::label4
Referenced by pageWPF.
Label pageWPF::label5
Referenced by pageWPF.
Label pageWPF::label6
Referenced by pageWPF.
Label pageWPF::label7
Referenced by pageWPF.
Label pageWPF::label8
Button pageWPF::okayButton
Button pageWPF::cancelButton
List pageWPF::myList
bool pageWPF::handle
event ButtonClickHandler pageWPF::OnButtonClicked
Referenced by ButtonClicked, GetHwnd.
ScrollViewer pageWPF::myScroll
Button pageWPF::myButton
Referenced by pageWPF.
ComboBox pageWPF::myCombo
Referenced by CreateMyItem, pageWPF.
ComboBoxItem pageWPF::myItem
Referenced by CreateMyItem, pageWPF.
Grid pageWPF::myGrid
Referenced by pageWPF.
TextBox pageWPF::myText
Referenced by pageWPF, WPFButtonClicked.
delegate void pageWPF::ButtonClickHandler(Object^, DBPageEventArgs^)
Referenced by GetHwnd.
pageWPF::pageWPF()
pageWPF::pageWPF(int height, int width)
References ButtonClicked, CreateButton, CreateCombo, CreateLabel, CreateMyItem, CreaTextBlock, ID, label1, label2, label3, label4, label5, label6, label7, myButton, myCombo, myGrid, myItem, myText.
Label pageWPF::CreateLabel(int column, int row, String^text)
Referenced by pageWPF.
void pageWPF::ButtonClicked(Object^sender, RoutedEventArgs^args)
References OnButtonClicked.
Referenced by pageWPF.
Button pageWPF::CreateButton(int column, int row, String^text)
Referenced by pageWPF.
ComboBox pageWPF::CreateCombo(int column, int row)
Referenced by pageWPF.
ComboBoxItem pageWPF::CreateMyItem(String^name, String^text)
References myCombo, myItem.
Referenced by pageWPF.
TextBox pageWPF::CreaTextBlock(int column, int row)
Referenced by pageWPF.