WPFcontrolDB.h
RECT rect
Referenced by CreateAHorizontalScrollBar, WndProc.
HWND dataDisplayLabel
Referenced by CreateDataDisplay.
HWND nameLabel
Referenced by CreateDataDisplay, WPFButtonClicked.
HWND addressLabel
HWND cityLabel
HWND stateLabel
HWND zipLabel
HWND GetHwnd(HWND parent, int x, int y, int width, int height)
References pageWPF::ButtonClickHandler, WPFPageHost::hostedPage, pageWPF::OnButtonClicked, WPFButtonClicked.
Referenced by WndProc.
HWND CreateAHorizontalScrollBar(HWND hwndParent, int sbHeight)
References hInst, rect.
void WPFButtonClicked(Object^sender, DBPageEventArgs^args)
References WPFPageHost::hostedPage, DBPageEventArgs::isOkay, pageWPF::myText, nameLabel.
Referenced by GetHwnd.
void CreateDataDisplay(HWND hWnd, int top, int left, int width)
References dataDisplayLabel, hInst, nameLabel.
Referenced by WndProc.