WPFcontrolDB.cpp
MAX_LOADSTRING
Referenced by _tWinMain.
HINSTANCE hInst
Referenced by CreateAHorizontalScrollBar, CreateDataDisplay, InitInstance, WndProc.
WCHAR szTitle[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by _tWinMain, InitInstance.
WCHAR szWindowClass[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by _tWinMain, InitInstance, MyRegisterClass.
HWND wpfHwnd
Referenced by WndProc.
ATOM MyRegisterClass(HINSTANCE hInstance)
References IDC_WPFCONTROLDB, IDI_SMALL, IDI_WPFCONTROLDB, szWindowClass, WndProc.
Referenced by _tWinMain.
BOOL InitInstance(HINSTANCE, int)
References hInst, szTitle, szWindowClass.
Referenced by _tWinMain.
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM)
References About, CreateDataDisplay, GetHwnd, hInst, IDD_ABOUTBOX, IDM_ABOUT, IDM_EXIT, rect, wpfHwnd.
Referenced by MyRegisterClass.
INT_PTR CALLBACK About(HWND, UINT, WPARAM, LPARAM)
Referenced by WndProc.
int APIENTRY _tWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPTSTR lpCmdLine, int nCmdShow)
References IDC_WPFCONTROLDB, IDS_APP_TITLE, InitInstance, MAX_LOADSTRING, MyRegisterClass, szTitle, szWindowClass.
HWND GetHwnd(HWND parent, int x, int y, int width, int height)
References pageWPF::ButtonClickHandler, WPFPageHost::hostedPage, pageWPF::OnButtonClicked, WPFButtonClicked.
Referenced by WndProc.
HWND CreateAHorizontalScrollBar(HWND hwndParent, int sbHeight)
References hInst, rect.
void CreateDataDisplay(HWND hWnd, int top, int left, int width)
References dataDisplayLabel, hInst, nameLabel.
Referenced by WndProc.
void WPFButtonClicked(Object^sender, DBPageEventArgs^args)
References WPFPageHost::hostedPage, DBPageEventArgs::isOkay, pageWPF::myText, nameLabel.
Referenced by GetHwnd.